# -*- coding: utf-8 -*-
"""retangularPolar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jufhLacc0hYWmaGo6Y-Kimio0OnRvCly
"""

import numpy as np

def retangularPolar(z):
  retangular = np.hypot(z.real, z.imag)
  retangular_2 = np.arctan(abs(z.imag)/abs(z.real))
  retangular_2 = retangular_2 * (180/np.pi)

  if z.real < 0 and z.imag > 0:
    retangular_2 += 90
  if z.real < 0 and z.imag < 0:
    retangular_2 += 180
  if z.real > 0 and z.imag < 0:
    retangular_2 += 270

  print('Z =', retangular, ' theta =', retangular_2)

real = float(input('Entre com o valor real: '))
imaginario = float(input('Entre com o valor imaginario: '))

z = complex(real, imaginario)
retangularPolar(z)

